version: '3'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13-alpine
    container_name: echo-clean-database
    restart: always
    environment:
      POSTGRES_DB: echo_clean_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    shm_size: 256mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d echo_clean_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer - Interface Web para administração
  adminer:
    image: adminer:4.8.1
    container_name: echo_clean_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: